<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from C:\xampp2\htdocs\drupal-test\sites\default\files\civicrm\ext\com.joineryhq.groupreg\xml/schema/CRM/Groupreg/GroupregEvent.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:2d557b418d26619649e8a06f7aa71100)
 */
use CRM_Groupreg_ExtensionUtil as E;

/**
 * Database access object for the GroupregEvent entity.
 */
class CRM_Groupreg_DAO_GroupregEvent extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_groupreg_event';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Uniq identifier
   *
   * @var int
   */
  public $id;

  /**
   * FK to Event
   *
   * @var int
   */
  public $event_id;

  /**
   * @var bool
   */
  public $is_hide_not_you;

  /**
   * FK to Tag
   *
   * @var int
   */
  public $related_contact_tag_id;

  /**
   * @var int
   */
  public $is_prompt_related;

  /**
   * @var int
   */
  public $is_primary_attending;

  /**
   * Pseudo-FK to civicrm_option_value for participant_role
   *
   * @var int
   */
  public $nonattendee_role_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_groupreg_event';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Groupreg Events') : E::ts('Groupreg Event');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'event_id', 'civicrm_event', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'related_contact_tag_id', 'civicrm_tag', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Uniq identifier'),
          'required' => TRUE,
          'where' => 'civicrm_groupreg_event.id',
          'table_name' => 'civicrm_groupreg_event',
          'entity' => 'GroupregEvent',
          'bao' => 'CRM_Groupreg_DAO_GroupregEvent',
          'localizable' => 0,
          'add' => NULL,
        ],
        'event_id' => [
          'name' => 'event_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Event'),
          'required' => TRUE,
          'where' => 'civicrm_groupreg_event.event_id',
          'table_name' => 'civicrm_groupreg_event',
          'entity' => 'GroupregEvent',
          'bao' => 'CRM_Groupreg_DAO_GroupregEvent',
          'localizable' => 0,
          'FKClassName' => 'CRM_Event_DAO_Event',
          'add' => NULL,
        ],
        'is_hide_not_you' => [
          'name' => 'is_hide_not_you',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Hide "Not You" message?'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_groupreg_event.is_hide_not_you',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_groupreg_event',
          'entity' => 'GroupregEvent',
          'bao' => 'CRM_Groupreg_DAO_GroupregEvent',
          'localizable' => 0,
          'add' => NULL,
        ],
        'related_contact_tag_id' => [
          'name' => 'related_contact_tag_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Tag ID to apply to contacts marked as additional participants.'),
          'description' => E::ts('FK to Tag'),
          'required' => FALSE,
          'import' => TRUE,
          'where' => 'civicrm_groupreg_event.related_contact_tag_id',
          'export' => TRUE,
          'default' => 'NULL',
          'table_name' => 'civicrm_groupreg_event',
          'entity' => 'GroupregEvent',
          'bao' => 'CRM_Groupreg_DAO_GroupregEvent',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_Tag',
          'add' => NULL,
        ],
        'is_prompt_related' => [
          'name' => 'is_prompt_related',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Prompt with related individuals on Additional Partipant forms?'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_groupreg_event.is_prompt_related',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_groupreg_event',
          'entity' => 'GroupregEvent',
          'bao' => 'CRM_Groupreg_DAO_GroupregEvent',
          'localizable' => 0,
          'add' => NULL,
        ],
        'is_primary_attending' => [
          'name' => 'is_primary_attending',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Primary participant is attendee'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_groupreg_event.is_primary_attending',
          'export' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_groupreg_event',
          'entity' => 'GroupregEvent',
          'bao' => 'CRM_Groupreg_DAO_GroupregEvent',
          'localizable' => 0,
          'add' => NULL,
        ],
        'nonattendee_role_id' => [
          'name' => 'nonattendee_role_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Non-attending participant role'),
          'description' => E::ts('Pseudo-FK to civicrm_option_value for participant_role'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_groupreg_event.nonattendee_role_id',
          'export' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_groupreg_event',
          'entity' => 'GroupregEvent',
          'bao' => 'CRM_Groupreg_DAO_GroupregEvent',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'groupreg_event', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'groupreg_event', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
